name: flutter_ios_security_suite
description: A Flutter package that integrates the IOSSecuritySuite iOS pod to provide enhanced iOS security features in Flutter applications.
version: 0.0.1
homepage: https://github.com/JAYDARANIYA/flutter_ios_security_suite

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterIosSecuritySuitePlugin

